EXEC SP_EmployeeMasterInsert
    @EmployeeName = 'John Doe', 
    @Fk_BranchId = 1, 
    @Address = '123 Main St', 
    @Mobile = '1234567890', 
    @SkypeId = 'johndoe123', 
    @CcEmail = 'johndoe@example.com', 
    @Fk_HeadDesignationId = 1, 
    @JoinDate = '2025-01-01', 
    @DutyHour = '09:00:00', 
    @LeftCompany = 0, 											 
    @LeftDate = NULL, 
    @UserName = 'johndoe', 
    @Password = 'password123', 
    @AadharNumber = '123456789012', 
    @EmployeeCode = 'EMP124', 
    @Fk_DesignationId = 1, 
    @Fk_DivisionId = 1, 
    @Fk_LocationId = 1, 
    @Fk_UserGroupId = 1, 
    @PinCode = 123456, 
    @Email = 'johndoe@example.com', 
    @BccEmail = 'manager@example.com', 
    @PANNumber = 'ABCDE1234F', 
    @Fk_GenderId = 1, 
    @BirthDate = '1990-01-01', 
    @Fk_ShiftId = 1, 
    @Photo = NULL, 
    @Signature = NULL, 
    @Fk_EmployeeTypeId = 1, 
    @LoginStatus = 'Active', 
    @SignaturePath = 'path/to/signature', 
    @CreatedBy = 1;


	SELECT * FROM Tbl_EmployeeMaster WHERE EmployeeCode = 'EMP123';

